CREATE TABLE IF NOT EXISTS posts (
  post_id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  owner_id INT REFERENCES users(user_id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

